import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { Provider } from '@/components/ui/provider';

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Provider>{children}</Provider>
        </Providers>
      </body>
    </html>
  );
}
